#!/usr/bin/env bash
#
# Open an app in Xcode.
#
#   ./scripts/open-xcode.sh              # the customer app (TimiNow)
#   ./scripts/open-xcode.sh vet          # the clinic console (TimiVet)
#   ./scripts/open-xcode.sh lab          # the Layout Lab
#
# The .xcodeproj is generated by xcodegen from Darwin/project.yml and is not
# in git, so opening a fresh clone means generating it first. Doing that by
# hand means being in the right directory, which is where this has gone wrong
# before; this script does not care where you run it from.
#
# It opens with the Xcode that `xcode-select -p` points at, not with whichever
# one LaunchServices feels like. With two Xcodes installed those are not the
# same app, and a project opened in one while builds run in the other is a
# long afternoon.

set -euo pipefail
cd "$(dirname "$0")/.."

case "${1:-customer}" in
  customer|ios|timinow) APP="apps/customer-mobile"; PROJECT="TimiNow" ;;
  vet|desktop|timivet)  APP="apps/vet-desktop";     PROJECT="TimiVet" ;;
  lab|layout|layoutlab) APP="apps/layout-lab";      PROJECT="LayoutLab" ;;
  *) echo "unknown app: $1 (try: customer, vet, lab)" >&2; exit 1 ;;
esac

command -v xcodegen >/dev/null || {
  echo "xcodegen is required: brew install xcodegen" >&2; exit 1; }

( cd "$APP/Darwin" && xcodegen generate >/dev/null )

# The workspace wraps the generated project and carries the package
# references; open it when there is one, and the bare project when there
# is not.
TARGET="$APP/Project.xcworkspace"
[ -d "$TARGET" ] || TARGET="$APP/Darwin/$PROJECT.xcodeproj"
[ -e "$TARGET" ] || { echo "xcodegen ran but $TARGET is missing." >&2; exit 1; }

XCODE="$(dirname "$(dirname "$(xcode-select -p 2>/dev/null || echo /)")")"
if [ -d "$XCODE" ] && [ "${XCODE##*.}" = "app" ]; then
  echo "opening $TARGET in $XCODE"
  open -a "$XCODE" "$TARGET"
else
  echo "opening $TARGET"
  open "$TARGET"
fi
