/**
 * Put each Worker's security headers on the pages it actually serves.
 *
 * The gap this closes, found by curling production rather than by reading the
 * code: every HTML page on every surface was served with NO security headers
 * at all. No Content-Security-Policy, no X-Frame-Options, no
 * X-Content-Type-Options, no Referrer-Policy, no Permissions-Policy. The API
 * responses carried all of them, which is what made it invisible — the headers
 * were declared, tested by eye on /api/*, and never reached a single page.
 *
 * The cause is one line of configuration. Every wrangler config sets
 * `run_worker_first: ["/api/*"]`, so Cloudflare's asset server answers every
 * other request directly and the Worker is never invoked. The code in each
 * Worker that copies SECURITY_HEADERS onto an asset response is real, correct,
 * and dead for HTML.
 *
 * `_headers` is the asset server's own mechanism and applies without invoking
 * anything. The alternative was `run_worker_first: true`, which would fix it by
 * running the Worker for every image and stylesheet — correct but wasteful, and
 * it makes the page's headers depend on Worker code continuing to do the right
 * thing forever.
 *
 * One source of truth either way: this reads the SECURITY_HEADERS each Worker
 * already exports and writes the matching file. `--check` fails the build when
 * a file and its Worker have drifted, so editing a CSP without regenerating is
 * a build failure rather than a page that quietly lost its policy.
 */

import { readFile, writeFile } from "node:fs/promises";

/** Worker module → the assets directory it serves. */
const SURFACES = [
  ["../src/index.js", "public"],
  ["../apps/vet-web/src/index.js", "apps/vet-web/public"],
  ["../apps/admin-console/src/index.js", "apps/admin-console/public"],
  ["../apps/blog/src/index.js", "apps/blog/public"],
  ["../apps/voice-gateway/src/index.js", "apps/voice-gateway/public"]
];

const BANNER = [
  "# Generated by scripts/sync-headers.mjs — do not edit.",
  "#",
  "# These are the same SECURITY_HEADERS the Worker sets on its API responses.",
  "# They have to be repeated here because `run_worker_first: [\"/api/*\"]` means",
  "# the Worker never runs for a page request, so the headers it sets in code",
  "# never reached any HTML. Regenerate with `npm run sync:headers`; the check",
  "# in `npm run check` fails if this file and the Worker disagree."
];

async function render(modulePath) {
  const module = await import(modulePath);
  const headers = module.SECURITY_HEADERS;
  if (!headers) throw new Error(`${modulePath} does not export SECURITY_HEADERS`);
  const lines = [...BANNER, "", "/*"];
  // Sorted, so the generated file does not churn when a constant is reordered.
  for (const name of Object.keys(headers).sort()) {
    lines.push(`  ${name}: ${headers[name]}`);
  }
  return `${lines.join("\n")}\n`;
}

const check = process.argv.includes("--check");
let drifted = 0;

for (const [modulePath, directory] of SURFACES) {
  const wanted = await render(modulePath);
  const file = `${directory}/_headers`;
  const existing = await readFile(file, "utf8").catch(() => null);
  if (existing === wanted) continue;
  if (check) {
    drifted += 1;
    console.error(existing === null
      ? `${file} is missing — that surface serves its pages with no security headers at all.`
      : `${file} no longer matches the SECURITY_HEADERS in ${modulePath.replace("../", "")}.`);
    continue;
  }
  await writeFile(file, wanted);
  console.log(`wrote ${file}`);
}

if (drifted) {
  console.error(`\n${drifted} surface(s) out of sync. Run \`npm run sync:headers\` and commit the result.`);
  process.exit(1);
}
console.log(check
  ? `sync-headers: ${SURFACES.length} surfaces serve their pages with the headers their Worker declares.`
  : `sync-headers: ${SURFACES.length} surfaces updated.`);
